package jplag.csharp;

public interface CSharpTokenConstants extends jplag.TokenConstants {
    int FILE_END = 0;

    int INVOCATION = 2;
    int OBJECT_CREATION = 3;
    int ARRAY_CREATION = 4;
    int ASSIGNMENT = 5;
    int L_BRACE = 6;
    int R_BRACE = 7;
    int DECLARE_VAR = 8;
    int DECLARE_CONST = 9;
    int IF = 10;
    int ELSE = 11;
    int SWITCH_BEGIN = 12;
    int SWITCH_END = 13;
    int CASE = 14;
    int DO = 15;
    int WHILE = 16;
    int FOR = 17;
    int FOREACH = 18;
    int BREAK = 19;
    int CONTINUE = 20;
    int GOTO = 21;
    int RETURN = 22;
    int THROW = 23;
    int CHECKED = 24;
    int UNCHECKED = 25;
    int LOCK = 26;
    int USING = 27;
    int TRY = 28;
    int CATCH = 29;
    int FINALLY = 30;
    int NAMESPACE_BEGIN = 31;
    int NAMESPACE_END = 32;
    int USING_DIRECTIVE = 33;
    int CLASS_BEGIN = 34;
    int CLASS_END = 35;
    int METHOD = 36;
    int PROPERTY = 37;
    int EVENT = 38;
    int INDEXER = 39;
    int OPERATOR = 40;
    int CONSTRUCTOR = 41;
    int STATIC_CONSTR = 42;
    int DESTRUCTOR = 43;
    int STRUCT_BEGIN = 44;
    int STRUCT_END = 45;
    int INTERFACE_BEGIN = 46;
    int INTERFACE_END = 47;
    int ENUM = 48;
    int DELEGATE = 49;
    int ATTRIBUTE = 50;
    int END_IF = 51;
    int UNSAFE = 52;
    int FIXED = 53;

    int NUM_DIFF_TOKENS = 54;
}
